In [1]:
import numpy as np

## numpy basics 

In [9]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result += u[i]*v[i]

    return result 

u = np.array([1,2,3])
v = np.array([7,8,9])
print(vector_vector_multiplication(u,v))
print(u.dot(v))

50


In [12]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    result = np.zeros(u.shape[0])

    for i in range(u.shape[0]):
        result[i] += vector_vector_multiplication(u[i], v)

    return result

u = np.array([
    [1,2,3],
    [10,11,12],
    [20,21,22]
    ])
v = np.array([7,8,9])
print( matrix_vector_multiplication(u,v))
print(u.dot(v))

[ 50. 266. 506.]
[ 50 266 506]


In [14]:
def matrix_matrix_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    result = np.zeros((u.shape[0], v.shape[1]))

    for i in range(v.shape[1]):
        vi = v[:,i]
        uvi = matrix_vector_multiplication(u, vi)
        result[:, i] = uvi

    return result


u = np.array([
    [1,2,3],
    [10,11,12],
    [20,21,22]
    ])
v = np.array([
    [7,8],
    [3,2],
    [3,4]
])

print(matrix_matrix_multiplication(u,v))
print(u.dot(v))

[[ 22.  24.]
 [139. 150.]
 [269. 290.]]
[[ 22  24]
 [139 150]
 [269 290]]


1.5.3
